# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 21:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='polarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='readability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='subjectivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'P', b'Gender fluid')], default=b'P', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
