# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_auto_20160313_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'P', b'Gender fluid')], max_length=1),
        ),
    ]
